name: Push Container to Heroku

on: 
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Login to Heroku Container registry
      env: 
        HEROKU_API_KEY: ${{ secrets.REACTJS_CICD_HEROKU }}
      run: heroku container:login 
    - name: Build and push
      env:
        HEROKU_API_KEY: ${{ secrets.REACTJS_CICD_HEROKU }}
      run: heroku container:push -a 'reactjs-cicd-init-dev' web 
    - name: Release
      env:
        HEROKU_API_KEY: ${{ secrets.REACTJS_CICD_HEROKU }}
      run: heroku container:release -a 'reactjs-cicd-init-dev' web 